import { NextResponse } from 'next/server';

// Static plugin registry — Phase 6 will move this to DB
const PLUGINS = [
  {
    id: 'web-search',
    name: 'Web Search',
    description: 'Give agents real-time web search via Tavily or SerpAPI',
    category: 'research',
    author: 'AIX Core',
    stars: 1240,
    installs: 8900,
    installed: false,
    free: true,
    tags: ['search', 'real-time', 'research'],
  },
  {
    id: 'code-exec',
    name: 'Code Executor',
    description: 'Sandboxed Python/JS execution for agents — Vercel Sandbox powered',
    category: 'code',
    author: 'AIX Core',
    stars: 980,
    installs: 5400,
    installed: false,
    free: true,
    tags: ['python', 'javascript', 'sandbox'],
  },
  {
    id: 'pdf-reader',
    name: 'PDF Reader',
    description: 'Extract and chunk PDF documents for RAG pipelines',
    category: 'data',
    author: 'AIX Core',
    stars: 760,
    installs: 4100,
    installed: false,
    free: true,
    tags: ['pdf', 'rag', 'documents'],
  },
  {
    id: 'slack-notifier',
    name: 'Slack Notifier',
    description: 'Send agent results and alerts directly to Slack channels',
    category: 'communication',
    author: 'AIX Labs',
    stars: 520,
    installs: 2300,
    installed: false,
    free: true,
    tags: ['slack', 'notifications', 'webhook'],
  },
  {
    id: 'csv-analyzer',
    name: 'CSV Analyzer',
    description: 'Parse and analyze CSV/Excel files with agent reasoning',
    category: 'data',
    author: 'AIX Labs',
    stars: 440,
    installs: 1900,
    installed: false,
    free: true,
    tags: ['csv', 'excel', 'analytics'],
  },
  {
    id: 'github-tool',
    name: 'GitHub Tool',
    description: 'Let agents read repos, create issues, review PRs autonomously',
    category: 'code',
    author: 'AIX Core',
    stars: 1100,
    installs: 6700,
    installed: false,
    free: true,
    tags: ['github', 'git', 'code-review'],
  },
  {
    id: 'memory-store',
    name: 'Long-term Memory',
    description: 'Persistent vector memory across sessions — Upstash Vector powered',
    category: 'utility',
    author: 'AIX Core',
    stars: 890,
    installs: 3800,
    installed: false,
    free: false,
    tags: ['memory', 'vector', 'persistence'],
  },
  {
    id: 'image-vision',
    name: 'Image Vision',
    description: 'Pass images to agents via GPT-4o Vision for analysis tasks',
    category: 'research',
    author: 'AIX Labs',
    stars: 670,
    installs: 2900,
    installed: false,
    free: false,
    tags: ['vision', 'images', 'gpt-4o'],
  },
  {
    id: 'cron-scheduler',
    name: 'Cron Scheduler',
    description: 'Schedule agent tasks to run on cron intervals via Vercel Cron',
    category: 'utility',
    author: 'AIX Core',
    stars: 380,
    installs: 1600,
    installed: false,
    free: true,
    tags: ['cron', 'scheduler', 'automation'],
  },
];

export async function GET() {
  return NextResponse.json({ plugins: PLUGINS, total: PLUGINS.length });
}
